name: LearningOS CI
on: #which event starts this workflow?
  pull_request:
    branches: 
      - main
jobs:
  frontend-validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: npm ci # CI never modifies lock file 
        working-directory: frontend
      - name: Build Frontend
        run: npm run build
        working-directory: frontend

        # adding lint 
      - name: Run ESLint
        working-directory: frontend
        run: npm run lint
      
        